version: "3.9"

services:
  backend:
    build: ./backend
    container_name: games-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: videogames
      DB_PORT: 5432
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: games-web
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: https://2bxcdcs4-3000.uks1.devtunnels.ms
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules